app/models.py
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin, current_user
from datetime import datetime
from . import db
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
  return User.query.get(int(user_id))



class User(UserMixin, db.Model):
  __tablename__ = 'users'
  
  id = db.Column(db.Integer, primary_key=True)
  first_name = db.Column(db.String(255))
  last_name = db.Column(db.String(255))
  username = db.Column(db.String(255), unique=True, index=True)
  email = db.Column(db.String(255), unique=True, index=True)
  password_hash = db.Column(db.String(255))
  bio = db.Column(db.String(255))
  profile_pic_path = db.Column(db.String(255))
  playlist = db.relationship('Playlist', backref='user', lazy='dynamic')

  @property
  def password(self):
    raise AttributeError('you cannot read the password')
  
  @password.setter
  def password(self, password):
    self.password_hash = generate_password_hash(password)
    
  def verify_password(self, password):
    return check_password_hash(self.password_hash, password)
  
  def __repr__(self):
      return f'User {self.username}'


class Radio(db.Model):
  __tablename__ = 'radios'
  
  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(200))
  url = db.Column(db.String(255))
  favicon = db.Column(db.String(255))
  votes = db.Column(db.Integer)
  
    
class Playlist(db.Model):
  
  __tablename__ = 'playlists'

  id = db.Column(db.Integer,primary_key=True)
  url = db.Column(db.String(255))
  subtitle = db.Column(db.String(255))
  title = db.Column(db.String(255))
  image = db.Column(db.String(255))
  users_id = db.Column(db.Integer, db.ForeignKey('users.id'))

  def __repr__(self):
        return f"Playlist('{self.url}')"
      
      
class Chart(db.Model):

  __tablename__ = 'charts'

  id = db.Column(db.Integer,primary_key=True)
  url = db.Column(db.String(255))
  subtitle = db.Column(db.String(255))
  title = db.Column(db.String(255))
  image = db.Column(db.String(255))
  users_id = db.Column(db.Integer, db.ForeignKey('users.id'))

  def __repr__(self):
        return f"Playlist('{self.url}')"

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import InputRequired,Length
from ..models import User

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [InputRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_assets import Environment, Bundle
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

db = SQLAlchemy()
mail = Mail()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


photos = UploadSet('photos',IMAGES)

def create_app(config_name):
  '''function to create and configure the Flask app'''
  app = Flask(__name__, static_folder='assets')
  app.config.from_object(config_options[config_name])
  
  db.init_app(app)
  login_manager.init_app(app)
  configure_uploads(app,photos)
  mail.init_app(app)
  
  assets = Environment(app)
  assets.url = app.static_url_path
  
  sass = Bundle('sass/global.scss', filters='pyscss', depends='sass/**/*.scss', output='styles/global.css')
  
  assets.config['PYSCSS_LOAD_PATHS'] = assets.load_path
  assets.config['PYSCSS_STATIC_URL'] = assets.url
  assets.config['PYSCSS_STATIC_ROOT'] = assets.directory
  assets.config['PYSCSS_ASSETS_URL'] = assets.url
  assets.config['PYSCSS_ASSETS_ROOT'] = assets.directory
  
  assets.register('sass_all', sass)
  sass.build()
  
  '''import and register the main blueprint'''
  from .main import main as main_blueprint
  app.register_blueprint(main_blueprint)
  
  from .auth import auth as auth_blueprint
  app.register_blueprint(auth_blueprint, url_prefix='/auth')
  
  '''import and configure the requests for use in the app'''
  from .requests import configure_request
  configure_request(app)
  
  
  return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views, errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from flask_login import login_required, current_user
from datetime import datetime as dt
from ..models import User
from .forms import UpdateProfile
from ..requests import get_afrobeats, get_blues, get_charts, get_dancehall, get_latin, get_playlist, get_pop, get_rock, get_station, get_world, search_music

from .. import db,photos
from . import main

@main.route('/')
def index():
  # stations = get_station()
  playlist = get_playlist()
  charts = get_charts()
  world = get_world()
  pop = get_pop()
  '''function that renders the homepage'''
  title = 'All in One Music App'
  
  

  return render_template('index.html', title=title, playlist=playlist, charts=charts, world=world, pop=pop)

@main.route('/trending')
def trending():
  afrobeats = get_afrobeats()
  blues = get_blues()
  pop = get_pop()
  world = get_world()
  '''function that renders the homepage'''
  title = 'All in One Music App'



  return render_template('trending.html', title=title, afrobeats=afrobeats, pop=pop, blues=blues, world=world,)

@main.route('/collections')
def collections():
  dancehall = get_dancehall()
  latin = get_latin()
  rock = get_rock()
  afrobeats = get_afrobeats()
  
  '''function that renders the homepage'''
  title = 'All in One Music App'
  
  

  return render_template('collections.html', title=title,  dancehall=dancehall, latin=latin, rock=rock, afrobeats=afrobeats)

@main.route('/user/<uname>')
def profile(uname):
  user = User.query.filter_by(username = uname).first()

  if user is None:
    abort(404)

  return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()

    return redirect(url_for('main.profile',uname=uname))


@main.route('/search')
def find():
  title = 'Search'
  search_music = request.args.get('query')
  if search_music:
    return redirect(url_for('main.search', query=search_music, title=title))
  
  else:
    return render_template('find.html')
  
  
  
@main.route('/search/<query>')
def search(query):
	query_list = query.split(' ')
	query_format = "+".join(query_list)
	search_tracks = search_music(query_format)
	title = f'search results for {query}'
  
  
	return render_template('search.html',title=title, music=search_tracks)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;300;400;500;600;700;800;900&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='styles/global.css')}}"
    />
    {% if title %}
    <title>Truebarz | {{title}}</title>
    {% else %}
    <title>Truebarz | The Music App</title>
    {% endif %}
  </head>
  <body id="app">
    {% block content %}{% endblock %}
    <footer id="footer">
      <p class="text">made with &#10084;</p>
      <p class="copy">&#169; 2022</p>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  </body>
</html>

app/templates/card.html
{% extends 'base.html' %} {% import 'macros.html' as macro %} {% block content
%} {% include 'navbar.html' %}

<div id="radio-card">
  <img
    class="icon"
    src="{{url_for('static', filename='icons/radio.svg')}}"
    alt="radio"
  />
  <p class="text">Radio station</p>
</div>

<div id="artist-card">
  <img
    class="icon"
    src="{{url_for('static', filename='icons/user.svg')}}"
    alt="artist"
  />
  <p class="text">Radio station</p>
</div>

<div id="lyric-card">
  <img
    class="icon"
    src="{{url_for('static', filename='icons/user-music.svg')}}"
    alt="lyric"
  />
  <div class="content">
    <p class="name">Artist Name</p>
    <p class="song">Song Title</p>
  </div>
</div>

{% endblock %}

app/templates/collections.html
{% extends 'base.html' %} {% import 'macros.html' as macro %} {% block content
%} {% include 'navbar.html' %}

<div id="collections">
  <section class="playlist">
    <div class="header">
      <div class="content">
        <h1 class="title">Dancehall Vibes</h1>
        <p class="text">curated just for you</p>
      </div>
      <a class="round" href="#">view all</a>
    </div>
    <div class="charts">{{macro.displayCharts(dancehall)}}</div>
  </section>
  <section class="playlist">
    <div class="header">
      <div class="content">
        <h1 class="title">Contemporary Rock</h1>
        <p class="text">from around the world</p>
      </div>
      <a class="round" href="#">view all</a>
    </div>
    <div class="lyrics">{{macro.displaySourceList(rock)}}</div>
  </section>
</div>

<div id="categories">
  <section class="playlist">
    <div class="header">
      <div class="content">
        <h1 class="title">Latin hitlist</h1>
        <p class="text">From the world of latin</p>
      </div>
      <a class="round" href="#">view all</a>
    </div>
    <div class="charts">{{macro.displayCharts(latin)}}</div>
  </section>
  <section class="artist">
    <div class="header">
      <div class="content">
        <h1 class="title">New artists</h1>
        <p class="text">from around the world</p>
      </div>
      <a class="round" href="#">view all</a>
    </div>
    <div class="lyrics">{{macro.displaySourceList(afrobeats)}}</div>
  </section>
</div>

{% endblock %}

app/templates/find.html
{% extends 'base.html' %} {% block content %}
<section class="find">
  <form>
    <input type="text" name="query" placeholder="search..." />
    <button type="submit">
      <img
        class="icon"
        src="{{url_for('static', filename='icons/search.svg')}}"
        alt="search"
      />
    </button>
  </form>
</section>
{% endblock %}

app/templates/four_ow_four.html
{% extends 'base.html' %} {% block content %}
<section class="not-found">
  <h1>Ooooops!</h1>
  <p>This page cannot be found</p>
</section>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %} {% import 'macros.html' as macro %} {% block content
%} {% include 'navbar.html' %}

<!-- Hero Section -->
<section id="hero">
  <div class="content">
    <h2 class="title">For True Music Lovers</h2>
    <p class="text">
      Identify and Stream the Latest Music,<br />
      On the Go
    </p>
    <button class="btn">GET STARTED</button>
  </div>
</section>

<div id="categories">
  <section class="playlist">
    <div class="header">
      <div class="content">
        <h1 class="title">Trending today</h1>
        <p class="text">curated just for you</p>
      </div>
      <a class="round" href="#">view all</a>
    </div>
    <div class="charts">{{macro.displayCharts(world)}}</div>
  </section>
  <section class="playlist">
    <div class="header">
      <div class="content">
        <h1 class="title">Todays Playlist</h1>
        <p class="text">from around the world</p>
      </div>
      <a class="round" href="#">view all</a>
    </div>
    <div class="lyrics">{{macro.displaySourceList(charts)}}</div>
  </section>
</div>

<!-- <div id="categories">
  <section class="radio">
    <div class="header">
      <div class="content">
        <h1 class="title">Internet Radio</h1>
        <p class="text">curated just for you</p>
      </div>
      <a class="round" href="#">view all</a>
    </div>
    <div class="cards">{{macro.displaySources(main_stations)}}</div>
  </section>
</div> -->
<div id="categories">
  <section class="playlist">
    <div class="header">
      <div class="content">
        <h1 class="title">Pop hitlist</h1>
        <p class="text">From the world of pop</p>
      </div>
      <a class="round" href="#">view all</a>
    </div>
    <div class="charts">{{macro.displayCharts(pop)}}</div>
  </section>
  <section class="artist">
    <div class="header">
      <div class="content">
        <h1 class="title">New artists</h1>
        <p class="text">from around the world</p>
      </div>
      <a class="round" href="#">view all</a>
    </div>
    <div class="lyrics">{{macro.displaySourceList(playlist)}}</div>
  </section>
</div>

{% endblock %}

app/templates/macros.html
{% macro displaySources(source_list) %} {% for source in source_list %}
<a id="radio-card" href="{{source.url}}">
  <div class="content">
    {% if source.favicon %}
    <img class="icon" src="{{source.favicon}}" alt="{{source.name}}" />
    {% else %}
    <img
      class="icon"
      src="{{url_for('static', filename='icons/radio.svg')}}"
      alt="radio"
    />
    {% endif %}
    <p class="text">{{source.name}}</p>
  </div>
</a>
{% endfor %} {% endmacro %} {% macro displaySourceList(playlist)%} {% for source
in playlist %}

<a id="lyric-card" href="{{source.url}}">
  <img class="icon" src="{{source.image}}" alt="image" />
  <div class="content">
    <p class="name">{{source.title}}</p>
    <p class="song">{{source.subtitle}}</p>
  </div>
</a>
{% endfor %} {% endmacro %} {% macro displayCharts(playlist)%} {% for source in
playlist %}

<a id="chart-card" href="{{source.url}}">
  <img class="icon" src="{{source.image}}" alt="image" />
  <div class="content">
    <p class="name">{{source.title}}</p>
    <p class="song">{{source.subtitle}}</p>
  </div>
</a>
{% endfor %} {% endmacro %}

app/templates/navbar.html
<nav id="navbar">
  <div class="left">
    <a class="link" href="/collections">
      <img
        class="icon"
        src="{{url_for('static', filename='icons/playlist.svg')}}"
        alt="playlist"
      />
    </a>
    <a class="link" href="/trending">
      <img
        class="icon"
        src="{{url_for('static', filename='icons/trend.svg')}}"
        alt="trend"
      />
    </a>
  </div>
  <div class="center">
    <a class="navbrand" href="/">
      <img
        class="logo"
        src="{{url_for('static', filename='icons/logo.svg')}}"
        alt="logo"
      />
      <p class="text">Truebarz</p>
    </a>
  </div>

  <div class="right">
    <a class="link" href="{{url_for('main.find')}}">
      <img
        class="icon"
        src="{{url_for('static', filename='icons/search.svg')}}"
        alt="search"
      />
    </a>
    {% if current_user.is_authenticated %}
    <a
      class="link"
      href="{{url_for('main.profile',uname=current_user.username)}}"
    >
      <img
        class="icon"
        src="{{url_for('static', filename='icons/user.svg')}}"
        alt="user"
      />

      <p class="text">{{current_user.username}}</p>
    </a>
    {% else %}
    <a class="link" href="{{url_for('auth.login')}}">
      <img
        class="icon"
        src="{{url_for('static', filename='icons/user.svg')}}"
        alt="user"
      />

      <p class="text">login</p>
    </a>
    {% endif %}
  </div>
</nav>

app/templates/profile/profile.html
{% extends 'base.html'%} {% block content %} {% include 'navbar.html' %}

<section class="start">
  <div id="profile">
    <div class="head">
      <div class="left">
        <div class="user">
          {% if user.profile_pic_path %}
          <img
            class="image"
            src="{{url_for('static', filename=user.profile_pic_path)}}"
            alt="{{user.username}}"
          />
          {% else %}
          <img
            class="image"
            src="../../assets/icons/profile/person-cirlce.svg"
            alt="person"
          />

          {% endif %}
          <p class="username">{{user.username}}</p>
          <p class="email">{{user.email}}</p>
          {% if user == current_user %}
          <form
            class="form"
            action="{{url_for('main.update_pic',uname=user.username)}}"
            method="post"
            enctype="multipart/form-data"
          >
            <input type="file" name="photo" class="form-control" required />
            <input type="submit" />
          </form>
          {% endif %}
        </div>
        <div class="bio">
          {% if user.first_name %}
          <h1>{{user.first_name}} {{user.last_name}}</h1>

          {%else%}
          <p class="text">Names not available</p>
          {% endif %} {% if user.bio %}
          <p>{{user.bio}}</p>
          {%else%}
          <p>No bio available</p>
          {% endif %}
        </div>
      </div>

      <div class="link">
        {% if user == current_user %}
        <a href="{{url_for('main.update_profile',uname=user.username)}}"
          >Edit profile</a
        >
        {% endif %}
      </div>
    </div>
  </div>
</section>
{%endblock%}

app/templates/profile/update.html
{% extends 'base.html' %} {% block content %}
<div id="login">
  <div class="login">
    <h2 class="title">Update Profile</h2>
    <
    <form class="form" method="post">
      {{form.csrf_token}} {{form.bio(class = "input", placeholder = "your bio
      goes here")}} {{form.submit(placeholder = "submit")}}
    </form>
  </div>
</div>
{% endblock %}

app/templates/search.html
{% extends 'base.html' %} {% import 'macros.html' as macro %} {% block content
%}
<section class="playlist">
  <div class="header">
    <div class="content">
      <p class="text">based on your search</p>
    </div>
    <a class="round" href="#">view all</a>
  </div>
</section>
{% endblock %}

app/templates/trending.html
{% extends 'base.html' %} {% import 'macros.html' as macro %} {% block content
%} {% include 'navbar.html' %}

<div id="trending">
  <section class="playlist">
    <div class="header">
      <div class="content">
        <h1 class="title">Afrobeats</h1>
        <p class="text">curated just for you</p>
      </div>
      <a class="round" href="#">view all</a>
    </div>
    <div class="charts">{{macro.displayCharts(afrobeats)}}</div>
  </section>
  <section class="playlist">
    <div class="header">
      <div class="content">
        <h1 class="title">Todays Playlist</h1>
        <p class="text">from around the world</p>
      </div>
      <a class="round" href="#">view all</a>
    </div>
    <div class="lyrics">{{macro.displaySourceList(world)}}</div>
  </section>
</div>

<div id="categories">
  <section class="playlist">
    <div class="header">
      <div class="content">
        <h1 class="title">Blues hitlist</h1>
        <p class="text">From the world of RnB</p>
      </div>
      <a class="round" href="#">view all</a>
    </div>
    <div class="charts">{{macro.displayCharts(blues)}}</div>
  </section>
  <section class="artist">
    <div class="header">
      <div class="content">
        <h1 class="title">Pop artists</h1>
        <p class="text">from around the world</p>
      </div>
      <a class="round" href="#">view all</a>
    </div>
    <div class="lyrics">{{macro.displaySourceList(pop)}}</div>
  </section>
</div>

{% endblock %}